### ISSUE TITLE
Unsuccessful `make` on aarch64

### ISSUE THREAD

**Issue by archanox** [zeldaret/oot#1165]
After successfully running `make setup` and then running `make` I get the following error.
```
mobian@mobian:~/oot$ make
tools/ZAPD/ZAPD.out btex -eh -tt ci8 -i assets/objects/object_dy_obj/back_of_hand.ci8.png -o build/assets/objects/object_dy_obj/back_of_hand.ci8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/beta_clothes.rgba16.png -o build/assets/objects/object_dy_obj/beta_clothes.rgba16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/beta_gradient_1.rgba16.png -o build/assets/objects/object_dy_obj/beta_gradient_1.rgba16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/beta_gradient_2.rgba16.png -o build/assets/objects/object_dy_obj/beta_gradient_2.rgba16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt ci8 -i assets/objects/object_dy_obj/boot_pattern.ci8.png -o build/assets/objects/object_dy_obj/boot_pattern.ci8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt ci8 -i assets/objects/object_dy_obj/ear_1.ci8.png -o build/assets/objects/object_dy_obj/ear_1.ci8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt ci8 -i assets/objects/object_dy_obj/ear_2.ci8.png -o build/assets/objects/object_dy_obj/ear_2.ci8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/eye_closed.rgba16.png -o build/assets/objects/object_dy_obj/eye_closed.rgba16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/eye_half.rgba16.png -o build/assets/objects/object_dy_obj/eye_half.rgba16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/eye_open.rgba16.png -o build/assets/objects/object_dy_obj/eye_open.rgba16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt ia16 -i assets/objects/object_dy_obj/flower.ia16.png -o build/assets/objects/object_dy_obj/flower.ia16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt ci8 -i assets/objects/object_dy_obj/hair.ci8.png -o build/assets/objects/object_dy_obj/hair.ci8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt ci8 -i assets/objects/object_dy_obj/leaves_pattern_1.ci8.png -o build/assets/objects/object_dy_obj/leaves_pattern_1.ci8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/leaves_pattern_2.rgba16.png -o build/assets/objects/object_dy_obj/leaves_pattern_2.rgba16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt ci8 -i assets/objects/object_dy_obj/leaves_pattern_3.ci8.png -o build/assets/objects/object_dy_obj/leaves_pattern_3.ci8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/mouth_closed.rgba16.png -o build/assets/objects/object_dy_obj/mouth_closed.rgba16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/mouth_open.rgba16.png -o build/assets/objects/object_dy_obj/mouth_open.rgba16.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt i4 -i assets/objects/object_dy_obj/particle.i4.png -o build/assets/objects/object_dy_obj/particle.i4.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt ci8 -i assets/objects/object_dy_obj/skin_gradient.ci8.png -o build/assets/objects/object_dy_obj/skin_gradient.ci8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt i8 -i assets/objects/object_dy_obj/spiral_beam_gradient.i8.png -o build/assets/objects/object_dy_obj/spiral_beam_gradient.i8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt i8 -i assets/objects/object_dy_obj/spiral_beam_pattern.i8.png -o build/assets/objects/object_dy_obj/spiral_beam_pattern.i8.inc.c
tools/ZAPD/ZAPD.out btex -eh -tt rgba16 -i assets/objects/object_dy_obj/tlut.rgba16.png -o build/assets/objects/object_dy_obj/tlut.rgba16.inc.c
python3 tools/asm_processor/build.py tools/ido_recomp/linux/7.1/cc -- mips-linux-gnu-as -march=vr4300 -32 -Iinclude -- -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -I. -Wab,-r4300_mul -woff 649,838,712  -mips2 -O2 -o build/assets/text/fra_message_data_static.o assets/text/fra_message_data_static.c
Traceback (most recent call last):
  File "/home/mobian/oot/tools/asm_processor/build.py", line 40, in <module>
    subprocess.check_call(compile_cmdline)
  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'tools/ido_recomp/linux/7.1/cc'
make: *** [Makefile:308: build/assets/text/fra_message_data_static.o] Error 1
mobian@mobian:~/oot$ 
```

**Comment by louist103** [comment]
> I was able to find this, https://github.com/Emill/ido-static-recomp but it still seems to use precompiled binaries. Is there source available to build them for different architectures?

You would need to cross compile with the repo. This branch while very old does that. 
https://github.com/louist103/oot/tree/IDO3/tools/ido_recomp

**Comment by archanox** [comment]
Would it be preferable to leave the source code in this repo (or as a submodule) so that non-x86 architectures can build out of the box? Or was there a reason why the pre-compiled binaries were swapped in?
I was hoping to get a RISC-V and PPC64 build next.

**Comment by louist103** [comment]
> Would it be preferable to leave the source code in this repo (or as a submodule) so that non-x86 architectures can build out of the box? Or was there a reason why the pre-compiled binaries were swapped in? I was hoping to get a RISC-V and PPC64 build next.

I had it but it added a good 5 minutes to the setup time so I never actually PRed it.  The thought was that if someone had that type of system and wanted to build they would have the knowledge to build IDO anyway.
